CREATE TABLE IF NOT EXISTS merimen_data (
    id INT PRIMARY KEY AUTO_INCREMENT,
    claim_action VARCHAR(255),
    merimen_case_id VARCHAR(255) NOT NULL UNIQUE,
    claim_type VARCHAR(255),
    insurance_claim_no VARCHAR(255) NOT NULL UNIQUE,
    insured_name VARCHAR(255),
    insured_id_no VARCHAR(255),
    insured_tel VARCHAR(255),
    insured_veh_reg_no VARCHAR(255),
    date_of_loss DATE,
    time_of_loss TIME,
    policy_cover_note_no VARCHAR(255),
    repairer_name VARCHAR(255),
    handling_insurer VARCHAR(255),
    claimant_insurer VARCHAR(255),
    assignment_date DATETIME,
    cancellation_date DATETIME,
    editing_date DATETIME,
    adj_asg_remarks TEXT,
    place_of_loss_postcode VARCHAR(255),
    recommended_reserve DECIMAL(10,2),
    adj_provi_fee DECIMAL(10,2),
    police_report_date DATE,
    police_report_time TIME,
    status VARCHAR(255) DEFAULT 'NEW',
    is_processed BOOLEAN DEFAULT FALSE,
    processing_attempts INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Create composite unique index
    UNIQUE INDEX unique_claim_index (insured_veh_reg_no, date_of_loss, time_of_loss)
);
